version: 2

jobs:

  ios:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - run: yarn

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
            - node_modules

      - run:
          name: "Pre-launch iOS Simulator"
          command: xcrun instruments -w "iPhone 8 (11.2) [" || true

      - run:
          name: "Build iOS"
          # Hack -> git log outputed as error
          command: yarn tns build ios


  android:
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout

      ## install nvm, node, yarn
      - run:
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
            source ~/.nvm/nvm.sh
            nvm install 10
            curl -o- -L https://yarnpkg.com/install.sh | bash


      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - run: yarn

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
            - node_modules

      - run:
          name: "Build Android"
          command: yarn tns build android

workflows:
  version: 2
  build:
    jobs:
      - ios
      - android
