version: 2

jobs:

  ios:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout

      - restore_cache:
          name: "Restore Homebrew cache"
          key: homebrew-{{ .Branch }}-2019-02-22.2

      - run:
          name: "Update Homebrew"
          command: brew update

      - run:
          name: "Install operating system level build dependencies"
          environment:
            HOMEBREW_NO_AUTO_UPDATE: "1"
          command: brew bundle

      - save_cache:
          name: "Save Homebrew cache"
          key: homebrew-{{ .Branch }}-2019-02-22.2
          paths:
            - /usr/local/Homebrew
            - /usr/local/Cellar
            - ~/Library/caches/Homebrew


      - run:
          name: "Set Global NativeScript Settings"
          command: |
            mkdir -p ~/.local/share/.nativescript-cli
            cp user-settings.json ~/.local/share/.nativescript-cli

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - run: yarn

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
            - node_modules

      - run:
          name: "Install Python `six` package"
          command: pip install six


      # - run:
      #     name: "Pre-launch iOS Simulator"
      #     command: xcrun instruments -w "iPhone 8 (11.2) [" || true


      - run:
          name: "Build iOS"
          # Hack -> git log outputed as error
          command: NS_SKIP_ENV_CHECK=true yarn tns build ios


  android:
    docker:
      - image: scratchy/nativescript-cli
    environment:
      YARN: /root/.yarn/bin/yarn
      _JAVA_OPTIONS: -Xmx1g
    steps:
      - checkout

      ## install nvm, node, yarn
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - run: $YARN

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
            - node_modules

      - run:
          name: "Build Android"
          command: $YARN tns build android

workflows:
  version: 2
  build:
    jobs:
      - ios
      - android
